name: PRINTOUT

on:
  workflow_dispatch:
    inputs:
      branch:
        description: branch name, hash or tag
        required: true
        default: master
jobs:
  printHash:
    name: print hash of image
    runs-on: ubuntu-latest
    steps:
      - run: echo "Branch ${{github.event.inputs.branch}} - ${{ github.ref.name }}"
