name: PRINTOUT

on:
  workflow_dispatch:

jobs:
  printHash:
    name: print hash of image
    runs-on: ubuntu-latest
    steps:
      - run: echo "`Branch` ${{github.event.inputs.branch}} - ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
